from php:5-fpm

ADD postfixadmin-3.1.tar.gz /var/www/


RUN rm -rf /var/www/html \
    && mv /var/www/postfixadmin-3.1 /var/www/html \
    && chown -R www-data:www-data /var/www/html

RUN apt-get update && apt-get install -y libc-client-dev libkrb5-dev

RUN docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-install  mysqli

RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install imap

RUN sed -i "s@;php_flag.display_errors. = off@php_flag[display_errors] = on@" /usr/local/etc/php-fpm.d/www.conf 
RUN sed -i "s@;php_admin_value.error_log. @php_admin_value[error_log] @" /usr/local/etc/php-fpm.d/www.conf 
RUN sed -i "s@;php_admin_flag.log_errors. @php_admin_flag[log_errors] @" /usr/local/etc/php-fpm.d/www.conf 
RUN echo 'php_admin_value[date.timezone] = Europe/Paris' >> /usr/local/etc/php-fpm.d/www.conf
#RUN sed -i 's/;php_admin_value.memory_limit. = 32M/php_admin_value[memory_limit] = 256M/' /usr/local/etc/php-fpm.d/www.conf 


RUN chown -R www-data:www-data /var/www/html

ADD fpm-entrypoint.sh /fpm-entrypoint.sh

CMD ["/fpm-entrypoint.sh"]
