from nginx

ADD postfixadmin-3.1.tar.gz /var/www/
ADD nginx-postfixadmin.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /var/www/html \
    && mv /var/www/postfixadmin-3.1 /var/www/html \
    && chown -R www-data:www-data /var/www/html
